version: "3.9"

services:
  backend-service:
    image: ctrlf-back-main-backend-service
    container_name: ctrlf-backend
    ports:
      - "9003:9003"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - ctrlf-back-network

networks:
  ctrlf-back-network:
    external: true
    name: ctrlf-back-main_default
