spring:
  datasource:
    url: jdbc:postgresql://keycloak-db:5432/keycloak
    username: keycloak
    password: keycloak

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak-service:8090/auth/realms/ctrlf

keycloak:
  admin:
    base-url: http://keycloak-service:8090
    realm: ctrlf
    client-id: infra-admin
    client-secret: changeme

app:
  rag:
    ai:
      base-url: http://ai-service.argocd.svc.cluster.local:8000
      token: changeme
      timeout-seconds: 50
  api:
    education-service:
      base-url: http://education-service:9002
      timeout-seconds: 10