apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: 858507113889.dkr.ecr.ap-northeast-2.amazonaws.com/argocd/chat-service:latest
          ports:
            - containerPort: 9005 # Spring Boot 앱 포트
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod" # 배포할 때
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "https://8bang-ctrlf.com/auth/realms/ctrlf"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
              value: "http://keycloak-service:8090/auth/realms/ctrlf/protocol/openid-connect/certs"
            #  value: "dev"  #개발할 때
            - name: AI_INTERNAL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ai-api-secrets
                  key: AI_INTERNAL_TOKEN
            - name: AI_SERVICE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ai-api-secrets
                  key: AI_SERVICE_TOKEN
            - name: AI_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ai-api-secrets
                  key: AI_API_TOKEN
#      nodeSelector:
#         zone: private
# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: chat-service
#   namespace: ctrl
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: chat-service
#   template:
#     metadata:
#       labels:
#         app: chat-service
#     spec:
#       containers:
#         - name: chat-service
#           image: 858507113889.dkr.ecr.ap-northeast-2.amazonaws.com/argocd/chat-service:latest
#           ports:
#             - containerPort: 9005 # Spring Boot 앱 포트
#           imagePullPolicy: Always
#           env:
#             - name: SPRING_PROFILES_ACTIVE
#               value: "prod" # 배포할 때
#             - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
#               value: "https://8bang-ctrlf.com/auth/realms/ctrlf"
#             - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
#               value: "http://keycloak-service:8090/auth/realms/ctrlf/protocol/openid-connect/certs"
#             #  value: "dev"  #개발할 때
#             - name: AI_INTERNAL_TOKEN
#               valueFrom:
#                 secretKeyRef:
#                   name: ai-api-secrets
#                   key: AI_INTERNAL_TOKEN
#             - name: AI_SERVICE_TOKEN
#               valueFrom:
#                 secretKeyRef:
#                   name: ai-api-secrets
#                   key: AI_SERVICE_TOKEN
#             - name: AI_API_TOKEN
#               valueFrom:
#                 secretKeyRef:
#                   name: ai-api-secrets
#                   key: AI_API_TOKEN
#       imagePullSecrets:
#         - name: ecr-registry-helper
# #      nodeSelector:
# #         zone: private
