apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-service
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-service
  template:
    metadata:
      labels:
        app: quiz-service
    spec:
      containers:
        - name: quiz-service
          # 여기에 아까 성공한 ECR 이미지 주소를 정확히 넣으세요a
          image: 858507113889.dkr.ecr.ap-northeast-2.amazonaws.com/argocd/quiz-service:732ba9f3453d6c4219579b1191d5bf00fd0c26e4
          ports:
            - containerPort: 9004 # Spring Boot 앱 포트
          imagePullPolicy: Always
