apiVersion: batch/v1
kind: Job
metadata:
  name: education-seed-job
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - name: education-service
          image: 858507113889.dkr.ecr.ap-northeast-2.amazonaws.com/argocd/education-service:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod,prod-seed" # 시드 전용 프로파일 활성화
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://keycloak-db:5432/keycloak"
            - name: SPRING_DATASOURCE_USERNAME
              value: "keycloak"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "keycloak"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update" 
            - name: AI_INTERNAL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ai-api-secrets
                  key: AI_INTERNAL_TOKEN
            - name: AI_SERVICE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ai-api-secrets
                  key: AI_SERVICE_TOKEN
            - name: AI_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ai-api-secrets
                  key: AI_API_TOKEN
      restartPolicy: OnFailure