spring:
  datasource:
    url: jdbc:postgresql://ctrl.c7yyi6w0ch43.ap-northeast-2.rds.amazonaws.com:5432/db
    username: postgres
    password: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://10.0.147.41:8090/realms/ctrlf
ai:
  gateway:
    url: http://192.168.0.112:8000
